deepseek_key = "sk-d2cd9c045a4442a8adb35a09e110f794"
PAYPAL_CLIENT_ID = "AevS4AsgJJKUSpFDJUjZWXVKjH7cKifwUubIJW1a5ZS7ikHF7N3IhrJhq9IKlGuELVrtqFSW7swzS6CB"
PAYPAL_CLIENT_SECRET = "EFXJx3j5Df8Kx1KaOPPdYvWYQx9Y4kXltQHiHA6FK6rAzh3cIUQUKtpMng1ubnMHGsEsUkNaeU9joFkg"